// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWGo8o8E65xxCOEXjBLVMmA0zxjVQO-Uk',
    appId: '1:849403735979:web:862f865eb0097674f3acee',
    messagingSenderId: '849403735979',
    projectId: 'hirfa2-b0920',
    authDomain: 'hirfa2-b0920.firebaseapp.com',
    storageBucket: 'hirfa2-b0920.appspot.com',
    measurementId: 'G-LET57EZENM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCghIUagsqAoAlhjKiIu4JqREeUsTbts6o',
    appId: '1:849403735979:android:676d9c2f0c881c0af3acee',
    messagingSenderId: '849403735979',
    projectId: 'hirfa2-b0920',
    storageBucket: 'hirfa2-b0920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Vkv7vVPWPOvuEv0nNrHw98nTQYJMeQg',
    appId: '1:849403735979:ios:93e3db7ab6218b26f3acee',
    messagingSenderId: '849403735979',
    projectId: 'hirfa2-b0920',
    storageBucket: 'hirfa2-b0920.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Vkv7vVPWPOvuEv0nNrHw98nTQYJMeQg',
    appId: '1:849403735979:ios:22d347387240e4e7f3acee',
    messagingSenderId: '849403735979',
    projectId: 'hirfa2-b0920',
    storageBucket: 'hirfa2-b0920.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
